[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "docKar"
version = "0.0.1"
authors = [
    {name = "Lovro Grgurić Mileusnić", email = "lovrogm@gmail.com"}
]
requires-python = ">=3.9"


[project.scripts]
dockar = "docKar.generate:main"